### ISSUE TITLE
Useful make options

### ISSUE THREAD

**Issue by eliotb** [keith-packard/snek#21]
Building snek, a couple of useful options worth documenting for the Makefile

To install in your home dir rather than systemwide  `make PREFIX=$HOME/.local`   

To avoid trying to build for other hosts something like `make SNEK_OTHEROS=0 SNEK_OTHEROS_DIR=hosts/linux`

**Comment by keith-packard** [comment]
I've added your suggestions to README.md. Thanks much for the idea!
