### ISSUE TITLE
Release binary files in releases?

### ISSUE THREAD

**Issue by zoobab** [keith-packard/snek#29]
Would it be possible to release binary files when you make releases?

Like provide on .bin file to flash on an ESP32 for example...

**Comment by keith-packard** [comment]
You bet. I already do this for the Debian package; creating a stand-alone zip file will be easy.

**Comment by keith-packard** [comment]
Oh, that reminds me -- did you see the 'dist' directory on sneklang.org? That has windows/mac/linux bits all packaged and ready to use.

[sneklang/dist](https://sneklang.org/snek/dist/)

I'll be adding a simple zipfile with just the portable bits to that in the future.

**Comment by keith-packard** [comment]
All done. Next release will include snek-1.4.zip
