### ISSUE TITLE
PyCon APAC 2020 keynote invitation

### ISSUE THREAD

**Issue by tangingw** [keith-packard/snek#31]
Hi Keith,

I am not too sure if you have received our invitation (we have sent two mails before we submit this as an issue). We would like to invite you to speak as keynote speaker for PyCon APAC 2020. The venue and date: 19 - 20 September 2020, Kota Kinabalu, Sabah, Malaysia.  

Best regards,
@tangingw

**Comment by keith-packard** [comment]
Working on this :-)
