### ISSUE TITLE
Programs for snek for Posix requires an extra newline in order to be loaded

### ISSUE THREAD

**Issue by mobluse** [keith-packard/snek#39]
Programs for Snek 1.7 for Posix requires an extra newline after the last line with code in order to be loaded.  
`snek --interactive hello.py`  
If I don't have an extra newline I get:  
`hello.py:4 Syntax error at "".`  
`python3 -i hello.py` handles this.

I compiled Snek using this repository and run on Raspberry Pi 4 B with Raspberry Pi OS Buster. I installed lola from your repo here. I did this because there were no precompiled version for my system.

**Comment by keith-packard** [comment]
Can you paste the example that fails so I can test? I found several 'hello.py' on the net and they look like this:
```
print('hello world')
```
This example works fine.

**Comment by mobluse** [comment]
Here is a file with `hello1.py` that doesn't work with `snek hello1.py` on my system:
[hello1.zip](https://github.com/keith-packard/snek/files/7481664/hello1.zip)
It works with `python3 hello1.py`. `hello1.py` lacks a newline (\x0A) at the end. I wrote the file in Mousepad 0.4.1.
