### ISSUE TITLE
32bit integers? structures?

### ISSUE THREAD

**Issue by fanoush** [keith-packard/snek#5]
Hi Keith, this looks nice, however how does the "single numeric data type, 32-bit floats" work with handling 16 and 32bit access to HW registers? Because of size I am thinking about using Snek for tiny firmware running on fitness tracker but I am puzzled how useful it is with single datatype without objects/structs. How could I make  some C based API (e.g. bluetooth) available to snek code with just 32bit floats?

BTW, the tracker is CC2541 based (8051) and there is BlueBasic ported to this chip https://github.com/kscheff/BlueBasic and it kind of works for me but  I hate basic with line numbers and goto/gosub :-)

Also I have another tracker based on Dialog 14585/6 which only has 96KB for data and code in total so it it is tight fit for Micropython or Espruino.

So I am searching for something smaller, between C and micropython/espruino but I guess I need at least strings and/or 8/6/32 bit arrays.

**Comment by keith-packard** [comment]
Snek is certainly limited, but I've created a GPIO interface for an Arduino which you might check out to see whether that makes any sense for you. Snek does have strings, lists and tuples to store more complicated values, but it doesn't have dictionaries or objects. I can imagine adding dictionaries as those are fairly straightforward, but adding objects would increase the size of the language rather dramatically.

As for 8/16/32 bit arrays, lists of floats can hold all of those values. Translating between them and any underlying hardware requiring those precise sizes would need to be done by implementing new builtin functions. Those are easy to add to snek; again, the GPIO code for arduino might provide some useful information.

**Comment by fanoush** [comment]
Thanks. I tried the posix version and indeed there are strings and lists so a lot can be done with it. However I guess I cannot store and do math with full 32bit long values  as current poly type cannot hold it. Well in fact variant with long default type instead of float (i.e. with no floats at all) could be interesting and possibly less heavy (both for speed and code size as softfloat math could be removed). Anyway even when keeping float datatype as is the float based lists may be inefficient for storing and manipulating binary data (e.g bitmaps and fonts for oled display, framebuffer) so I guess at least adding bytearray type would be useful and not that hard. Or maybe strings could be abused for that if the underlying buffer is accessible.

Dictionaries sound interesting if it is easy, objects are not needed indeed.

**Comment by keith-packard** [comment]
Feel free to experiment with the code and change it however you like; let me know what you manage to do!

**Comment by fanoush** [comment]
from issue #7
> If we want to get that 24th bit back, we can use the sign bit too.

I am still toying with idea about more value types than just float. So if you keep sign bit as a marker for reference types (=those stored in snek_pool that need offset/pointer) then positive NaN values can store different value types than float. So if I keep highest bits as 0x7fc (so it is still a NaN) i can have 2-6 highest bits to store value type and 16-20 bits to store value so I can have signed/unsigned 8/16bit values (or even chars/wchars). I know with interpreter the speed won't be great anyway but still using float as a base type on AVR or non-F ARM Cortex for all arithmetics (including bitwise operators and shifts) feels a bit wasteful. I don't understand the grammar and parsing parts of snek, would integer value types add too much complexity so it is out of question?

Also there are only four reference types limited by lowest 2 bits, so for more types one of highest bits (23,22) could be used too  as I'd wish to have at least byte arrays. I guess current list would not do? as I can store different types there like e.g. ["hhhh",5,6] so it cannot be packed byte array to store binary data e.g. bitmaps.

**Comment by keith-packard** [comment]
Adding integers and other types would be possible; you'd need to fix the lexer to detect input which didn't have an exponent or fractional part and have those return a different token and value, then add that token to the parser right next to the existing NUMBER entry. After that, it's a matter of creating an instruction to hold immediate values and adding code for all of the existing operators in snek_code_run to check for them and act accordingly.

Feel free to email me with explicit questions and code for review; it's certainly a good way to explore computer languages.

I would also like to add dictionaries at some point; those would at least offer a datatype that wasn't an array.

**Comment by keith-packard** [comment]
> Just and idea, is zero offset a valid one? What happens when you store list type (lowest 2 bits =0) as  first element at
>  offset zero? Wouldn't this be encoded as -inf?

Oh, that's definitely a bug.

**Comment by keith-packard** [comment]
Ok, thanks for pointing this case out. Took a while to sort out, but I've pushed a patch which fixes this by using type 0 for 'builtin' (which uses the 'offset' bits to encode the builtin id, which starts at 1). Then I changed the value for a 'NULL' offset from 0 to ~3 -- a non-zero value, which happens to look like a builtin (as it has type bits of zeros). That made the memory manager changes smaller.

Finding and fixing all places which assumed that a NULL offset was encoded as 0 took a bit of time, but I think it's working now.

Thanks a ton for thinking about this and finding this problem; the chances of a list landing at 0 was small, so when that happened and the system crashed, we'd be very confused.

**Comment by fanoush** [comment]
> Thanks a ton for thinking about this and finding this problem

Well I was thinking about those value types added as positive NaN values and wanted to use all integers including zero so it hit me I need to make sure the rest is not zero. My simplest solution was to waste one highest bit with it making sure it is always NaN. However I guess I can start the type enum from 1 too.

As for the NUMBER token I am thinking about reusing it for integers too (they are numbers too) and have number type stored as part of (or next to) [snek_token_val](https://github.com/keith-packard/snek/blob/master/snek.h#L349).

BTW I see you have some attempt to have 8 bit integers here https://github.com/keith-packard/snek/blob/master/snek-code.c#L292 so native integer when parsing would help here even if snek values are floats. Also as an index into array it would make sense. Currently you allow float indexes which may possibly cause unexpected issues with rounding and low precision. Does integer values stored in float always result in exact integer when adding/substracting/multiplying another integer? I hope so but if not it may sometimes select different element.

```
> a=[1,2,3]
> a[1.9999999]
2
> a[1.99999999999]
3
>
> 0.99999995
0.9999999
> 0.99999996
0.9999999
> 0.99999997
0.9999999
> 0.99999998
1
```
btw, python3 gives "TypeError: list indices must be integers or slices, not float"

**Comment by keith-packard** [comment]
You might consider subscribing to the snek mailing list so these conversations could be shared with other snek developers (just myself and one other person at present)...

Integer to float and back is 'exact' for integers within the size of the significand -- in the case of a 32-bit float, as long as the value is between -(1<<23) and (1<<23) - 1, then converting to float and back will yield an exact result with no fractional value.

Have fun playing!

**Comment by fanoush** [comment]
> You might consider subscribing to the snek mailing list so these conversations could be shared with other snek developers

Oh, sorry. Makes sense. Next time I'll post to the list.  And now I remember you already mentioned it before and I didn't get the hint.
