### ISSUE TITLE
Upstream https://keithp.com/cgit/apps.git/?

### ISSUE THREAD

**Issue by xiaoxiang781216** [keith-packard/snek#60]
From https://sneklang.org/:

Snek in NuttX
[NuttX](https://nuttx.org/) is a moderate-sized embedded RTOS that works on a variety of small systems. I've written the necessary glue-code and build instructions to make Snek available there. All of that code is licensed under the standard NuttX/BSD license, but because NuttX upstream is not willing to take code that references GPL code, I've created a [fork of the NuttX app tree in my git repository.](https://keithp.com/cgit/apps.git/).

NuttX has a good mechanism for adding code of this sort; there are no changes to existing NuttX files, just a new directory in app/interpreters/snek. When present, all of the necessary options become visible in the regular NuttX configuration tool.

This port doesn't interface to much of NuttX yet, it would be fun to see some experimentation here.

But, the community accept the GPL code if it download from internet, there even has an option to enable GPL component:
https://github.com/apache/incubator-nuttx/blob/master/Kconfig#L33-L41

So, it's better to upstream your porting to help people try snek quickly.

**Comment by keith-packard** [comment]
That appears to be a change from when I first looked into this. I'm not using NuttX at this point, so I probably won't get around to working on upstreaming these bits. If you're interested, please feel free!
