### ISSUE TITLE
underscore variable?

### ISSUE THREAD

**Issue by incanus** [keith-packard/snek#72]
Have you considered adding the underscore (`_`) variable to the interactive REPL? Per the main [Python docs](https://docs.python.org/3/reference/lexical_analysis.html#reserved-classes-of-identifiers): 

> Separately, the interactive interpreter makes the result of the last evaluation available in the variable `_`. (It is stored in the [builtins](https://docs.python.org/3/library/builtins.html#module-builtins) module, alongside built-in functions like `print`.)

Notably, this never gets set to `None`.

**Comment by keith-packard** [comment]
Sure, this seems easy enough. I had to compress some other code a bit to make room, but that led to
a new helper function, `snek_id_store`, which replaced a repeated pattern in the code and so made a nice
simplification and cleanup.
