### ISSUE TITLE
compilation fails on Picolibc semihosting for qemu-arm

### ISSUE THREAD

**Issue by sanyaade-teachings** [keith-packard/snek#84]
Hi All,

Good day to everyone and many thanks for snek and all your amazing efforts
I am having small issue getting snek to build fully on Ubuntu 20.04 on WSL. The build fails on semihosting as shown below:
The error message:
**/usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: cannot find /usr/lib/picolibc/arm-none-eabi/lib/thumb/v7-m/nofp/crt0-semihost.o: No such file or directory
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:33: snek-qemu-arm-1.9.elf] Error 1
make[1]: Leaving directory '/home/lookma/snek/ports/qemu-arm'
make: *** [Makefile:30: ports/qemu-arm/snek-qemu-arm-1.9.elf] Error 2**
![image](https://github.com/keith-packard/snek/assets/4993211/be6e7857-1bf7-4fcb-a97b-99e2f1545b82)

I followed all the install steps as detailed on Snek GitHub pages.
 
Please help for tips and directions!
Hear from you soon!

God blesses!!!

Regards

**Comment by keith-packard** [comment]
You'll need a newer version of picolibc for this to work -- version 1.7.5 or newer, which means upgrading to ubuntu 22.10 or later. Good luck!

**Comment by sanyaade-teachings** [comment]
> You'll need a newer version of picolibc for this to work -- version 1.7.5 or newer, which means upgrading to ubuntu 22.10 or later. Good luck!

Many thanks!
Following your direction, 
I upgrade the Ubuntu distro to version 23.10
build snek again. It all went well.
![image](https://github.com/keith-packard/snek/assets/4993211/0dd2be6d-9df9-4dae-aa20-c22fbd798167)


Many thanks!
Next is to learn the basic steps requiring hardware porting with snek.
Many thanks!

God blesses!!!

Regards
